language: go

go:
  - 1.14.x

script:
  - go get -t -v ./...
  - bash ./go_test.sh

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - bash <(curl -Ls https://coverage.codacy.com/get.sh) report --language Go --force-language
